language: go

go:
  - 1.9

sudo: false

before_install:
  - export GOPATH=$HOME/gopath/src/github.com/owenliang/bigpipe
  - export PATH=$PATH:$HOME/gopath/src/github.com/owenliang/bigpipe/bin/
  - go get -v github.com/Masterminds/glide
  - cd src/github.com/Masterminds/glide && go install && cd -
  - mkdir -p ./bin && cp `which glide` ./bin

script:
  - sh build.sh